# Generated by Django 4.2.7 on 2023-12-13 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_comment_options_alter_customuser_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='img',
            field=models.ImageField(blank=True, default='./media/profile_images/default_img.jpg', null=True, upload_to='profile_images/'),
        ),
    ]
