# Generated by Django 4.2.7 on 2023-12-02 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20231201_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='feature_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
