# Generated by Django 4.2.7 on 2023-11-28 12:21

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=True, null=True, populate_from='title', unique=True),
        ),
    ]
