# Generated by Django 4.2.7 on 2023-12-01 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_customuser_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
