# Generated by Django 3.2.23 on 2023-11-29 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_cat',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
