# Generated by Django 3.2.23 on 2023-12-11 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default='Hii this is the discription', max_length=120),
        ),
        migrations.AddField(
            model_name='tag',
            name='description',
            field=models.TextField(default='Hii this is the discription', max_length=120),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.CharField(blank=True, default='Bhilwara', max_length=80),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='country',
            field=models.CharField(blank=True, choices=[('AF', 'Afghanistan'), ('DZ', 'Algeria'), ('AR', 'Argentina'), ('AU', 'Australia'), ('BD', 'Bangladesh'), ('BE', 'Belgium'), ('BJ', 'Benin'), ('BO', 'Bolivia'), ('BR', 'Brazil'), ('BF', 'Burkina Faso'), ('KP', 'Cambodia'), ('CM', 'Cameroon'), ('CA', 'Canada'), ('TD', 'Chad'), ('CL', 'Chile'), ('CN', 'China'), ('CO', 'Colombia'), ('CU', 'Cuba'), ('CZ', 'Czech Republic'), ('CD', 'Democratic Republic of the Congo'), ('DO', 'Dominican Republic'), ('EC', 'Ecuador'), ('EG', 'Egypt'), ('SV', 'El Salvador'), ('ET', 'Ethiopia'), ('FR', 'France'), ('DE', 'Germany'), ('GH', 'Ghana'), ('GR', 'Greece'), ('GT', 'Guatemala'), ('GN', 'Guinea'), ('HT', 'Haiti'), ('HN', 'Honduras'), ('IN', 'India'), ('ID', 'Indonesia'), ('IR', 'Iran'), ('IQ', 'Iraq'), ('IT', 'Italy'), ('CI', 'Ivory Coast'), ('JP', 'Japan'), ('KZ', 'Kazakhstan'), ('KE', 'Kenya'), ('MG', 'Madagascar'), ('MW', 'Malawi'), ('MY', 'Malaysia'), ('ML', 'Mali'), ('MX', 'Mexico'), ('MA', 'Morocco'), ('NP', 'Nepal'), ('NL', 'Netherlands'), ('NE', 'Niger'), ('NG', 'Nigeria'), ('KP', 'North Korea'), ('PK', 'Pakistan'), ('PE', 'Peru'), ('PH', 'Philippines'), ('PL', 'Poland'), ('PT', 'Portugal'), ('RO', 'Romania'), ('RU', 'Russia'), ('RW', 'Rwanda'), ('SA', 'Saudi Arabia'), ('SN', 'Senegal'), ('SO', 'Somalia'), ('ZA', 'South Africa'), ('KR', 'South Korea'), ('LK', 'Sri Lanka'), ('SD', 'Sudan'), ('SY', 'Syria'), ('TW', 'Taiwan'), ('TZ', 'Tanzania'), ('TH', 'Thailand'), ('TN', 'Tunisia'), ('TR', 'Turkey'), ('UG', 'Uganda'), ('UA', 'Ukraine'), ('GB', 'United Kingdom'), ('US', 'United States'), ('UZ', 'Uzbekistan'), ('VE', 'Venezuela'), ('VN', 'Vietnam'), ('YE', 'Yemen'), ('ZM', 'Zambia'), ('ZW', 'Zimbabwe')], default='India', max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=60),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.PositiveBigIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='state',
            field=models.CharField(blank=True, default='Rajasthan', max_length=90),
        ),
    ]
