# Generated by Django 3.2.23 on 2023-11-29 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_cat',
        ),
    ]
