# Generated by Django 4.2.7 on 2023-12-27 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_post_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
