# Generated by Django 4.2.7 on 2023-12-29 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('it', 'Italian'), ('pt', 'Portuguese'), ('ru', 'Russian'), ('ja', 'Japanese'), ('zh-CN', 'Chinese (Simplified)'), ('ar', 'Arabic'), ('hi', 'Hindi'), ('ko', 'Korean'), ('tr', 'Turkish'), ('nl', 'Dutch'), ('sv', 'Swedish'), ('fi', 'Finnish'), ('no', 'Norwegian'), ('da', 'Danish'), ('pl', 'Polish'), ('vi', 'Vietnamese'), ('th', 'Thai'), ('id', 'Indonesian'), ('ms', 'Malay'), ('he', 'Hebrew'), ('el', 'Greek'), ('cs', 'Czech'), ('hu', 'Hungarian'), ('ro', 'Romanian'), ('bg', 'Bulgarian'), ('uk', 'Ukrainian'), ('sk', 'Slovak'), ('sl', 'Slovenian'), ('hr', 'Croatian'), ('sr', 'Serbian'), ('mk', 'Macedonian'), ('sq', 'Albanian'), ('et', 'Estonian'), ('lv', 'Latvian'), ('lt', 'Lithuanian'), ('hy', 'Armenian'), ('ka', 'Georgian'), ('uz', 'Uzbek'), ('kk', 'Kazakh'), ('ky', 'Kyrgyz'), ('tg', 'Tajik'), ('tk', 'Turkmen'), ('mn', 'Mongolian'), ('ps', 'Pashto'), ('fa', 'Persian'), ('ur', 'Urdu'), ('bn', 'Bengali'), ('pa', 'Punjabi'), ('gu', 'Gujarati'), ('or', 'Odia'), ('mr', 'Marathi'), ('ne', 'Nepali'), ('si', 'Sinhala'), ('ml', 'Malayalam'), ('kn', 'Kannada'), ('ta', 'Tamil'), ('te', 'Telugu'), ('ur', 'Urdu'), ('am', 'Amharic'), ('sw', 'Swahili'), ('yo', 'Yoruba'), ('ha', 'Hausa'), ('ig', 'Igbo'), ('zu', 'Zulu'), ('xh', 'Xhosa'), ('af', 'Afrikaans'), ('is', 'Icelandic'), ('ga', 'Irish'), ('mt', 'Maltese'), ('th', 'Thai'), ('km', 'Khmer'), ('lo', 'Lao'), ('my', 'Burmese'), ('si', 'Sinhala'), ('ka', 'Georgian'), ('mn', 'Mongolian'), ('dz', 'Dzongkha'), ('yi', 'Yiddish'), ('jw', 'Javanese'), ('su', 'Sundanese'), ('ms', 'Malay'), ('fil', 'Filipino'), ('ceb', 'Cebuano'), ('hmn', 'Hmong'), ('haw', 'Hawaiian'), ('sm', 'Samoan'), ('to', 'Tongan'), ('mi', 'Maori'), ('fj', 'Fijian')], max_length=100),
        ),
    ]
