# Generated by Django 4.2.7 on 2023-12-29 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_alter_language_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
