# Generated by Django 4.2.7 on 2023-11-28 12:21

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='que_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=True, null=True, populate_from='question_text', unique=True),
        ),
    ]
